apps:
  - name: stranger-things
    script: ./index.js
    exec_mode: cluster
    watch: false
    instances: 2
    max_memory_restart: 200M
    env:
      PORT: 3000
      UPSIDE_DOWN: false
      PM2_PUBLIC_KEY: 0qbmw2xgqlf1gnp
      PM2_SECRET_KEY: x3880y9imz6wk90